// ============================================================================
// Instructions module — re-exports all instruction handlers
// ============================================================================

pub mod ai_reward_stake;
pub mod apply_pending;
pub mod claim_depin_faucet;
pub mod claim_faucet;
pub mod confidential_mint;
pub mod confidential_transfer;
pub mod configure_confidential;
pub mod create_metaplex_metadata;
pub mod deposit;
pub mod exchange_gift_card;
pub mod grow_vault;
pub mod init_treasury;
pub mod initialize_mint;
pub mod merchant_payment;
pub mod mint_bearer_note;
pub mod offline_confidential_transfer;
pub mod proposal;
pub mod quantum_realm;
pub mod redeem_bearer_note;
pub mod register_merchant;
pub mod seedless_onboard;
pub mod stake;
pub mod transfer_with_fee;
pub mod unstake;
pub mod vote;
pub mod withdraw;
pub mod zk_tax_report;

pub use ai_reward_stake::*;
pub use apply_pending::*;
pub use claim_depin_faucet::*;
pub use claim_faucet::*;
pub use confidential_mint::*;
pub use confidential_transfer::*;
pub use configure_confidential::*;
pub use create_metaplex_metadata::*;
pub use deposit::*;
pub use exchange_gift_card::*;
pub use grow_vault::*;
pub use init_treasury::*;
pub use initialize_mint::*;
pub use merchant_payment::*;
pub use mint_bearer_note::*;
pub use offline_confidential_transfer::*;
pub use proposal::*;
pub use quantum_realm::*;
pub use redeem_bearer_note::*;
pub use register_merchant::*;
pub use seedless_onboard::*;
pub use stake::*;
pub use transfer_with_fee::*;
pub use unstake::*;
pub use vote::*;
pub use withdraw::*;
pub use zk_tax_report::*;
