#!/usr/bin/env node
/* ============================================================================
 * OST · GAMES LIFECYCLE — real Switchboard randomness, real OST, real edge
 * ----------------------------------------------------------------------------
 * What this proves, on devnet, with real tokens:
 *
 *   1. initialize_house  — one PDA-owned vault backs every payout; the treasury
 *                          that takes the edge is PINNED here.
 *   2. fund_house        — the vault is capitalised with real OST.
 *   3. commit_bet        — the player escrows OST against a Switchboard
 *                          randomness account committed to a FUTURE slot. The
 *                          value DOES NOT EXIST YET: nobody (player, house, or
 *                          this script) can know or steer the outcome.
 *   4. settle_bet        — the oracle reveals; the PROGRAM reads the value,
 *                          derives the roll, and pays. We then RE-DERIVE the
 *                          roll ourselves from the revealed bytes and assert the
 *                          program agrees — that is what "verifiable" means.
 *
 * Contrast with docs/ost-games.js today, where the "server seed" is generated by
 * crypto.getRandomValues() in the PLAYER'S OWN BROWSER and kept in localStorage.
 * Anyone can read it and predict every roll. This settles that at the root.
 *
 * Exits non-zero on any mismatch.
 * ========================================================================== */
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import anchor from '@coral-xyz/anchor';
import {
  Connection, Keypair, PublicKey, SystemProgram, Transaction,
  TransactionInstruction, sendAndConfirmTransaction, LAMPORTS_PER_SOL, ComputeBudgetProgram
} from '@solana/web3.js';
import {
  TOKEN_2022_PROGRAM_ID, getAssociatedTokenAddressSync,
  createAssociatedTokenAccountIdempotentInstruction,
  createTransferCheckedInstruction, getAccount
} from '@solana/spl-token';
import {
  Randomness, asV0Tx, AnchorUtils, ON_DEMAND_DEVNET_QUEUE
} from '@switchboard-xyz/on-demand';

const RPC = process.env.OST_RPC || 'https://api.devnet.solana.com';
const MINT = new PublicKey('383pTzoZ8Gp83dzk23ZnvLcfX2Sq32TAGN48CMQu2pAJ');
const PROGRAM_ID = new PublicKey(
  JSON.parse(readFileSync(new URL('./program-id.json', import.meta.url), 'utf8')).programId);
const DEC = 9;
const HOUSE_FEE_BPS = 200;      // must equal HOUSE_FEE_BPS in the program

const KIND = { COINFLIP: 0, DICE: 1 };

const disc = (n) => createHash('sha256').update('global:' + n).digest().subarray(0, 8);
const u64 = (n) => { const b = Buffer.alloc(8); b.writeBigUInt64LE(BigInt(n)); return b; };
const ui = (n) => Number(n) / 10 ** DEC;
const raw = (n) => BigInt(Math.round(n * 10 ** DEC));
const link = (s) => `https://explorer.solana.com/tx/${s}?cluster=devnet`;

const authority = Keypair.fromSecretKey(Uint8Array.from(
  JSON.parse(readFileSync(process.env.USERPROFILE + '/.config/solana/id.json', 'utf8'))));
const conn = new Connection(RPC, 'confirmed');
const wallet = new anchor.Wallet(authority);

let fails = 0;
const say = (ok, m) => { console.log((ok ? '  PASS ' : '  FAIL ') + m); if (!ok) fails++; };

const [house] = PublicKey.findProgramAddressSync([Buffer.from('house'), MINT.toBuffer()], PROGRAM_ID);
const [vault] = PublicKey.findProgramAddressSync([Buffer.from('vault'), house.toBuffer()], PROGRAM_ID);
const treasuryAta = getAssociatedTokenAddressSync(MINT, authority.publicKey, true, TOKEN_2022_PROGRAM_ID);

const bal = async (a) => { try { return ui((await getAccount(conn, a, 'confirmed', TOKEN_2022_PROGRAM_ID)).amount); } catch { return 0; } };

// The house's books, straight from the chain.
function decodeHouse(d) {
  let o = 8 + 32 + 32 + 32;                 // authority, mint, treasury_token
  o += 2;                                   // bump, vault_bump
  const outstanding = ui(d.readBigUInt64LE(o)); o += 8;
  const wagered = ui(d.readBigUInt64LE(o)); o += 8;
  const paid = ui(d.readBigUInt64LE(o)); o += 8;
  const fees = ui(d.readBigUInt64LE(o));
  return { outstanding, wagered, paid, fees };
}
function decodeBet(d) {
  let o = 8 + 32 + 32 + 32;                 // player, mint, randomness
  const commitSlot = Number(d.readBigUInt64LE(o)); o += 8;
  const kind = d[o]; o += 1;
  const param = d[o]; o += 1;
  const stake = ui(d.readBigUInt64LE(o)); o += 8;
  const maxPayout = ui(d.readBigUInt64LE(o)); o += 8;
  o += 1;                                   // bump
  const settled = d[o] === 1; o += 1;
  const payout = ui(d.readBigUInt64LE(o)); o += 8;
  const fee = ui(d.readBigUInt64LE(o)); o += 8;
  const revealed = d.subarray(o, o + 8);
  return { commitSlot, kind, param, stake, maxPayout, settled, payout, fee, revealed };
}

// The SAME derivation the program uses: first 8 bytes, little-endian, mod 100.
const rollFrom = (revealed8) => Number(revealed8.readBigUInt64LE(0) % 100n);
// Fair odds (before the edge): coinflip 2x, dice 100/target.
const fairPayout = (kind, param, stake) =>
  kind === KIND.COINFLIP ? stake * 2 : stake * Math.floor(1_000_000 / param) / 10_000;

(async () => {
  console.log('OST · GAMES LIFECYCLE (Switchboard randomness, real OST on devnet)');
  console.log('  program ', PROGRAM_ID.toBase58(), '\n');

  const sbProgram = await AnchorUtils.loadProgramFromConnection(conn);
  // The SDK wants the queue's PUBKEY, not a Queue object (its typings say
  // `queue: web3.PublicKey`) — passing the object fails inside Anchor with
  // "Wrong input type for account queue".
  //
  // And `getDefaultDevnetQueue()` hands back a queue that DOES NOT EXIST on
  // devnet (verified: the account has no data). The live devnet queue is the
  // ON_DEMAND_DEVNET_QUEUE constant, owned by the devnet on-demand program.
  const queue = new PublicKey(ON_DEMAND_DEVNET_QUEUE.toString());
  const qInfo = await conn.getAccountInfo(queue);
  if (!qInfo) throw new Error('Switchboard devnet queue not found: ' + queue.toBase58());
  console.log('  queue   ', queue.toBase58(), '(Switchboard devnet)\n');

  // ---- 1) house ---------------------------------------------------------
  console.log('1) initialize_house');
  if (!(await conn.getAccountInfo(house))) {
    await sendAndConfirmTransaction(conn, new Transaction()
      .add(createAssociatedTokenAccountIdempotentInstruction(
        authority.publicKey, treasuryAta, authority.publicKey, MINT, TOKEN_2022_PROGRAM_ID))
      .add(new TransactionInstruction({
        programId: PROGRAM_ID,
        keys: [
          { pubkey: authority.publicKey, isSigner: true, isWritable: true },
          { pubkey: MINT, isSigner: false, isWritable: false },
          { pubkey: house, isSigner: false, isWritable: true },
          { pubkey: vault, isSigner: false, isWritable: true },
          { pubkey: treasuryAta, isSigner: false, isWritable: false },
          { pubkey: TOKEN_2022_PROGRAM_ID, isSigner: false, isWritable: false },
          { pubkey: SystemProgram.programId, isSigner: false, isWritable: false }
        ],
        data: disc('initialize_house')
      })), [authority], { commitment: 'confirmed' });
    console.log('   house created', house.toBase58());
  } else {
    console.log('   house already exists', house.toBase58());
  }

  // ---- 2) capitalise the vault -----------------------------------------
  const FUND = 300;
  console.log(`\n2) fund_house — the vault BACKS every payout (${FUND} OST)`);
  if ((await bal(vault)) < 200) {
    await sendAndConfirmTransaction(conn, new Transaction().add(new TransactionInstruction({
      programId: PROGRAM_ID,
      keys: [
        { pubkey: authority.publicKey, isSigner: true, isWritable: true },
        { pubkey: house, isSigner: false, isWritable: false },
        { pubkey: MINT, isSigner: false, isWritable: false },
        { pubkey: vault, isSigner: false, isWritable: true },
        { pubkey: treasuryAta, isSigner: false, isWritable: true },
        { pubkey: TOKEN_2022_PROGRAM_ID, isSigner: false, isWritable: false },
        { pubkey: SystemProgram.programId, isSigner: false, isWritable: false }
      ],
      data: Buffer.concat([disc('fund_house'), u64(raw(FUND))])
    })), [authority], { commitment: 'confirmed' });
  }
  console.log('   vault:', await bal(vault), 'OST');

  // ---- 3) player --------------------------------------------------------
  const player = Keypair.generate();
  const playerAta = getAssociatedTokenAddressSync(MINT, player.publicKey, true, TOKEN_2022_PROGRAM_ID);
  const src = getAssociatedTokenAddressSync(MINT, authority.publicKey, true, TOKEN_2022_PROGRAM_ID);
  const STAKE = 10;
  await sendAndConfirmTransaction(conn, new Transaction()
    .add(SystemProgram.transfer({ fromPubkey: authority.publicKey, toPubkey: player.publicKey, lamports: 0.1 * LAMPORTS_PER_SOL }))
    .add(createAssociatedTokenAccountIdempotentInstruction(authority.publicKey, playerAta, player.publicKey, MINT, TOKEN_2022_PROGRAM_ID))
    .add(createTransferCheckedInstruction(src, MINT, playerAta, authority.publicKey, raw(STAKE), DEC, [], TOKEN_2022_PROGRAM_ID)),
    [authority], { commitment: 'confirmed' });
  console.log(`\n3) player funded: ${STAKE} OST  ${player.publicKey.toBase58().slice(0, 8)}…`);

  // ---- 4) commit_bet — bet against a value that does not exist yet -------
  console.log('\n4) commit_bet — bound to randomness committed to a FUTURE slot');
  const rngKp = Keypair.generate();
  // Pass the payer EXPLICITLY. Without it the SDK falls back to its provider's
  // wallet — which, for a program loaded straight from a Connection, is a dummy
  // keypair whose account does not exist ("Account does not exist or has no
  // data"). Every one of these calls takes an optional payer; give it ours.
  const [randomness, createIx] = await Randomness.create(sbProgram, rngKp, queue, authority.publicKey);
  const commitIx = await randomness.commitIx(queue, authority.publicKey);

  const [bet] = PublicKey.findProgramAddressSync(
    [Buffer.from('bet'), player.publicKey.toBuffer(), randomness.pubkey.toBuffer()], PROGRAM_ID);

  // dice: win if roll < TARGET. Override to exercise a specific branch:
  //   --target 90  -> ~90% win (proves the payout + on-chain fee path)
  //   --target 50  -> fair coin
  const TARGET = Number(process.argv[process.argv.indexOf('--target') + 1]) || 50;
  const commitBetIx = new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: player.publicKey, isSigner: true, isWritable: true },
      { pubkey: house, isSigner: false, isWritable: true },
      { pubkey: MINT, isSigner: false, isWritable: false },
      { pubkey: vault, isSigner: false, isWritable: true },
      { pubkey: playerAta, isSigner: false, isWritable: true },
      { pubkey: bet, isSigner: false, isWritable: true },
      { pubkey: randomness.pubkey, isSigner: false, isWritable: false },
      { pubkey: TOKEN_2022_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false }
    ],
    data: Buffer.concat([disc('commit_bet'), Buffer.from([KIND.DICE]), Buffer.from([TARGET]), u64(raw(STAKE))])
  });

  // create + commit + our bet, all in ONE transaction: the bet is written in the
  // same slot the randomness is committed, so the value cannot already be known.
  const commitTx = await asV0Tx({
    connection: conn,
    ixs: [createIx, commitIx, commitBetIx],
    payer: authority.publicKey,
    signers: [authority, player, rngKp],
    computeUnitPrice: 75_000,
    computeUnitLimitMultiple: 1.4
  });
  const commitSig = await conn.sendTransaction(commitTx, { skipPreflight: false });
  await conn.confirmTransaction(commitSig, 'confirmed');
  console.log('   commit tx', link(commitSig));

  let betData = decodeBet((await conn.getAccountInfo(bet)).data);
  const vaultAfterBet = await bal(vault);
  say(betData.stake === STAKE, `stake ESCROWED on-chain: ${betData.stake} OST (vault now ${vaultAfterBet})`);
  say(betData.maxPayout === fairPayout(KIND.DICE, TARGET, STAKE),
    `max payout reserved against the vault: ${betData.maxPayout} OST (house cannot take a bet it can't pay)`);
  say(!betData.settled && betData.revealed.every((b) => b === 0),
    'no randomness revealed at bet time — the outcome does not exist yet');

  // ---- 5) settle_bet — the oracle reveals; the PROGRAM decides -----------
  console.log('\n5) settle_bet — oracle reveals, the program derives the roll');
  const revealIx = await randomness.revealIx(authority.publicKey);
  const settleIx = new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: authority.publicKey, isSigner: true, isWritable: true },  // permissionless settler
      { pubkey: house, isSigner: false, isWritable: true },
      { pubkey: MINT, isSigner: false, isWritable: false },
      { pubkey: bet, isSigner: false, isWritable: true },
      { pubkey: vault, isSigner: false, isWritable: true },
      { pubkey: playerAta, isSigner: false, isWritable: true },
      { pubkey: treasuryAta, isSigner: false, isWritable: true },
      { pubkey: randomness.pubkey, isSigner: false, isWritable: false },
      { pubkey: TOKEN_2022_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false }
    ],
    data: disc('settle_bet')
  });

  const pBefore = await bal(playerAta);
  const tBefore = await bal(treasuryAta);

  const settleTx = await asV0Tx({
    connection: conn,
    ixs: [revealIx, settleIx],
    payer: authority.publicKey,
    signers: [authority],
    computeUnitPrice: 75_000,
    computeUnitLimitMultiple: 1.4
  });
  const settleSig = await conn.sendTransaction(settleTx, { skipPreflight: false });
  await conn.confirmTransaction(settleSig, 'confirmed');
  console.log('   settle tx', link(settleSig));

  betData = decodeBet((await conn.getAccountInfo(bet)).data);
  const pAfter = await bal(playerAta);
  const tAfter = await bal(treasuryAta);

  // Re-derive the roll OURSELVES from the bytes the oracle revealed. If the
  // program agrees, the outcome is verifiable by anyone — which is the whole
  // point, and exactly what the browser-seed version could never offer.
  const roll = rollFrom(betData.revealed);
  const won = roll < TARGET;
  const gross = won ? fairPayout(KIND.DICE, TARGET, STAKE) : 0;
  const profit = Math.max(0, gross - STAKE);
  const feeExp = profit * HOUSE_FEE_BPS / 10000;
  const netExp = gross - feeExp;
  const near = (a, b) => Math.abs(a - b) < 1e-6;

  console.log(`\n   revealed bytes: ${betData.revealed.toString('hex')}`);
  console.log(`   roll = ${roll}  (target ${TARGET}) -> ${won ? 'WIN' : 'LOSS'}`);

  // Close the loop: the bytes the PROGRAM recorded must be the bytes the ORACLE
  // published. Without this we'd only be checking the program against itself.
  const rngState = await randomness.loadData();
  const oracleValue = Buffer.from(rngState.value).subarray(0, 8);
  say(oracleValue.equals(betData.revealed),
    `the bytes the program settled on ARE the oracle's published value (${oracleValue.toString('hex')})`);

  say(betData.settled, 'bet settled ON-CHAIN by the program');
  say(near(betData.payout, netExp),
    `payout matches the roll we independently re-derived: ${betData.payout} OST (expected ${netExp})`);
  say(near(pAfter - pBefore, netExp),
    `player balance moved by exactly the net payout: ${pBefore} -> ${pAfter}`);
  say(near(betData.fee, feeExp) && near(tAfter - tBefore, feeExp),
    won
      ? `house edge = ${HOUSE_FEE_BPS / 100}% of PROFIT only (${feeExp} OST) and landed in the pinned treasury`
      : 'a LOSS was not taxed (no profit, so no fee) — the stake is never raked');

  const h = decodeHouse((await conn.getAccountInfo(house)).data);
  say(near(h.outstanding, 0),
    `reservation released after settlement: outstanding liability back to ${h.outstanding} OST`);
  console.log(`   house books: wagered ${h.wagered} · paid ${h.paid} · fees ${h.fees} OST`);

  console.log(fails
    ? `\n${fails} FAIL`
    : '\n✅ VERIFIABLE RANDOMNESS: the player bet against a value that did not exist yet, a Switchboard oracle revealed it, the PROGRAM derived the roll, and we re-derived the same roll from the same bytes. Nobody could see or steer the outcome — unlike the browser-generated "server seed" the games use today.');
  process.exit(fails ? 1 : 0);
})().catch((e) => {
  console.error('\nFAILED:', e.message);
  if (e.logs) console.error(e.logs.slice(-15).join('\n'));
  process.exit(1);
});
